remote_theme : fongandrew/hydeout
#addition

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            zz on Hydeout
tagline:          '아아하하하핳'
description:      'The <a href="http://zzeang.github.io" target="_blank">zzeang</a> theme on <a href="https://hyde.getpoole.com/" target="_blank">Hydeout</a>.'
url:              "https://zzeang.github.io"
baseurl:          ""
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog indexs pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'zz'
  url:            https://twitter.com/fongandrewc

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
